name: build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_PR_NUM: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ! -z "${GH_PR_NUM}" ]]; then 
            echo "Checking out PR"
            git fetch origin pull/$GH_PR_NUM/head:tmp
            git checkout tmp
          fi
      - name: Run build script
        run: ./devSetup.sh
        shell: bash
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - name: Build dist
        run: yarn build
