name: pr-preview
on: pull_request_target
jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
      GH_PR_NUM:   ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      # Yes, we really want to checkout the PR
      - run: |
          git fetch origin pull/$GH_PR_NUM/head:tmp
          git checkout tmp
      - run: |
          git rev-parse origin/v6
          git rev-parse HEAD
          git rev-parse origin/v6..HEAD
          git log origin/v6..HEAD --format="%b"
      # Yes, we really want to checkout the PR
      # Injected by generate-workflows.js
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Load npm deps from cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-14-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint:js
        name: Lint JS
        if: always()
      - run: yarn lint:md
        name: Lint MD
        if: always()
      - run: yarn build
        name: Build component groups
      - uses: actions/cache@v2
        id: docs-cache
        name: Load webpack cache
        with:
          path: '.cache'
          key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
      - run: yarn build:docs
        name: Build docs
      - run: node .github/upload-preview.js packages/module/public
        name: Upload docs
        if: always()